import type { Metadata } from "next";
import { Figtree, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "./components/ui/NavBar";
import Footer from "./components/ui/Footer";
import "leaflet/dist/leaflet.css";


const figtreeSans = Figtree({
  variable: "--font-figtree-sans-serif",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
});


export const metadata: Metadata = {
  title: "Localcraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${figtreeSans.variable} ${instrumentSerif.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-col p-4 border-b-1">
            <NavBar />
          </div>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
